// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFjfwwCbDRMVEV4F1KIEj0nhanBLVL7oY',
    appId: '1:739405468797:web:1a8ca19b7e9c7dc3ef0d14',
    messagingSenderId: '739405468797',
    projectId: 'todo-emanuel-laairoy-rodrigo',
    authDomain: 'todo-emanuel-laairoy-rodrigo.firebaseapp.com',
    storageBucket: 'todo-emanuel-laairoy-rodrigo.appspot.com',
    measurementId: 'G-KN1TN8L04J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBkVwX88pmFPEfWAyMTY2D_XUk8LMGh20',
    appId: '1:739405468797:android:dda6172118334d3eef0d14',
    messagingSenderId: '739405468797',
    projectId: 'todo-emanuel-laairoy-rodrigo',
    storageBucket: 'todo-emanuel-laairoy-rodrigo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArRXfSSbMy7j5J9ADugxShmDCy70x5U74',
    appId: '1:739405468797:ios:09f88edc407a9960ef0d14',
    messagingSenderId: '739405468797',
    projectId: 'todo-emanuel-laairoy-rodrigo',
    storageBucket: 'todo-emanuel-laairoy-rodrigo.appspot.com',
    iosClientId: '739405468797-4et0sqm5l1lns5mk7c9c1998n51m060a.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
